### PR TITLE
Angelica Support

### PR DESCRIPTION
**Pull request by mitchej123**
Angelica Support
* Add Angelica as a compile time dependency
* Add the GTNH Maven
* Mark Renderers as thread safe with `@ThreadSafeISBRH`
* Move Tessellator.instance access into the methods so the ASM redirect properly supplies the CapturingTessellator

NOTE: Requires angelica 1.0.0-alpha19+ (not yet published)

### CODE REVIEW

**Comment by makamys** [comment]
Might be a good idea to get rid of `BlockModelBase`'s `tessellator` field so it doesn't get used for off-thread rendering by accident. Or at least change its name to something that discourages that kind of use, like `threadUnsafeTessellator`.

**Comment by mitchej123** [comment]
> Might be a good idea to get rid of `BlockModelBase`'s `tessellator` field so it doesn't get used for off-thread rendering by accident. Or at least change its name to something that discourages that kind of use, like `threadUnsafeTessellator`.

🤦 I did, but accidently reverted it when switching approaches

**Comment by Roadhog360** [comment]
Later we should also check if classes inherit annotations. If they do, you could move all of these annotations to `BlockModelBase` and I could just re-annotate any future renderers that happen to be unsafe, although I doubt I will ever write one.

**Review by Roadhog360 — APPROVED** [review]
sure

**Pull request merged**
