### PR TITLE
Split fence and gate

### PR DESCRIPTION
**Pull request by Wmaxlees**
This pull requests does 2 things;

1. Splits the config that allows us to enable/disable fences and enable/disable gates
2. Makes the non-classic woods (warped stem, cherry, etc.) gates, doors, fences, etc rely on the specific gates, doors, fences, etc. flags so that you can turn off cherry doors, for example, without losing all cherry blocks.

### CODE REVIEW

**Comment by Roadhog360** [comment]
The config values are supposed to only apply to vanilla blocks.

**Comment by Roadhog360** [comment]
Does this include your previous pull request for deepslate? It seems like it does.

**Comment by Wmaxlees** [comment]
It does. It's a mistake. I'll wait till that's either merged or rejected and then clean this one up. Sorry for the noise.

**Comment by Roadhog360** [comment]
It's alright. As for this pr... I am wondering if I want to introduce new config options for the gate/fence/woodredstone etc subset of blocks, specifically for the woods not in vanilla 1.7.10. The goal was to have the config toggles only apply to the vanilla woods, in case another mod adds them, which is why the new woods didn't have this value. If I were to accept this, then there'd no longer be a way to disable just those vanilla variants, in the case that another mod's adding them. I'm currently weighing in the potential value of new config options, and if it'd be worth making the config file larger for it

**Comment by Wmaxlees** [comment]
What about something like:

```
// Existing Configs
b:enableVanillaFences
b:enableVanillaWoodRedstone

// New Configs
b:enableVanillaGates
b:enableNewWoodGates
b:enableNewWoodFences
b:enableNewWoodRedstone
```

4 new entries to the config. Is that more bloat than you'd like?

**Comment by Roadhog360** [comment]
The problem with this is now, if we change its name, we are undoing the previous config choice people have made and has to be made again.

**Comment by Roadhog360** [comment]
Hm... I think I will accept this outcome. Will be re-reviewed after deepslate is merged

**Comment by Roadhog360** [comment]
Your previous PR has now been merged, so you can move forward with the cleanup you had planned here.

**Comment by Roadhog360** [comment]
> What about something like:
> 
> ```
> // Existing Configs
> b:enableVanillaFences
> b:enableVanillaWoodRedstone
> 
> // New Configs
> b:enableVanillaGates
> b:enableNewWoodGates
> b:enableNewWoodFences
> b:enableNewWoodRedstone
> ```
> 
> 4 new entries to the config. Is that more bloat than you'd like?

Is this still planned? Just makin sure

**Comment by Wmaxlees** [comment]
Yes. Still working through the change now that the rebase is done.

**Comment by Wmaxlees** [comment]
Done. We went from 5 -> 12 configs for this. Let me know if it's too much.

**Comment by Roadhog360** [comment]
Looks good. You forgot to apply enable new fences to WOOD_FENCE block though

**Comment by Wmaxlees** [comment]
Good catch. Added

**Comment by Roadhog360** [comment]
Umm I'm trying to merge this but it apparently has merge conflicts? I'm on mobile rn, can you please see what GitHub is complaining for?

**Comment by Wmaxlees** [comment]
It was some of the recipe checks for GTNH. It should be all merged properly now. Let me double check.

**Comment by Wmaxlees** [comment]
Yeah. Merge looks good to me.

**Pull request merged**
