### PR TITLE
zinc, magnesium, boron (ru_RU.lang)

### PR DESCRIPTION
**Pull request by kotmatross28729**
<details>

<summary>My suggestions regarding ores:</summary>

### Regular:

Sulfur [`oreSulfur`], 
Saltpeter (Potassium nitrate) [`oreSaltpeter`], 
Fluorite [`oreFluorite`], 
Beryllium [`oreBeryllium`], 
Cobalt [`oreCobalt`], 
Coltan [`oreColtan`]
Lignite ore [`oreLignite`]

###  Some (maybe) exclusives  for HNT: 

Australian ore [`oreAustralium`], 
Schrabidium ore [`oreSchrabidium`], 
Rare earth ore [`oreRareEarth`], 
Asbestos ore [`oreAsbestos`], 

</details>

### CODE REVIEW

**Comment by Roadhog360** [comment]
In your suggestions, can you provide examples of mods that actually add these?

**Comment by kotmatross28729** [comment]
[Hbms Nuclear Tech Mod](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT)

**Comment by kotmatross28729** [comment]
for "Regular" it is also gregtech

**Comment by Roadhog360** [comment]
GregTech does its own raw ores.

**Comment by kotmatross28729** [comment]
well, then HNT

**Pull request merged**
