### PR TITLE
Fix elytra not renders in first person

### PR DESCRIPTION
**Pull request by iocmet**

### CODE REVIEW

**Comment by Roadhog360** [comment]
@embeddedt What are your thoughts on this?

**Comment by embeddedt** [comment]
I haven't tested this change but at first glance I wonder if it will cause elytra on other players in multiplayer to not render.

**Comment by Roadhog360** [comment]
Will test when I get a chance.

**Comment by Roadhog360** [comment]
You are indeed correct, this completely breaks elytra rendering in multiplayer.

**Comment by Roadhog360** [comment]
image
image

**Comment by Roadhog360** [comment]
Are you able to remove that?

**Comment by embeddedt** [comment]
I don't remember how armor is rendered in 1.7 but it might be a good reference.

**Comment by Roadhog360** [comment]
This seems unecessary, surely another mixin isn't needed for this. Some mods render custom armor models withiut doing this.

**Comment by Roadhog360** [comment]
No, I mean like, is injection really the only way to fix this? This seems hazardous and may introduce incompatibilities.

**Comment by Roadhog360** [comment]
Will test soon, ty

**Comment by Roadhog360** [comment]
Testing now

**Pull request merged**
