### PR TITLE
footsteps are footsteps (ru_RU.lang)

### PR DESCRIPTION
**Pull request by kotmatross28729**
I understand correctly that you want the footsteps to remain footsteps , and the English version of the subtitles? (maybe i will do it tomorrow)

### CODE REVIEW

**Comment by GregoriusT** [comment]
Wait you changed the Bottle Fill and Empty thing, what does that have to do with Footsteps?

**Comment by kotmatross28729** [comment]
this refers to a previous pull request, where roadhog360, as I understand it, asked to change the sounds of footsteps / knocks to just footsteps (due to the fact that the sea lantern makes a sound of steps, I figured that this could be done)

**Comment by GregoriusT** [comment]
Just a random suggestion, why not just name the Sounds "Grass" instead of "Step on Grass", that way at least there cant be any confusion as to which action has been taken to the Grass.

**Comment by Roadhog360** [comment]
> I understand correctly that you want the footsteps to remain footsteps , and the English version of the subtitles? (maybe i will do it tomorrow)

You don't need to do an English version if you don't want to, I just asked for a quick translation of the few you added to understand what they say.

**Comment by Roadhog360** [comment]
> Just a random suggestion, why not just name the Sounds "Grass" instead of "Step on Grass", that way at least there cant be any confusion as to which action has been taken to the Grass.

Too much work and too far from vanilla behavior. More confusing and doesn't look as good.

**Comment by Roadhog360** [comment]
Also I'll close this, as it makes the bottle fill and empty messages the same. The bottle fill and bottle empty messages should not be the same; they should represent filling and emptying the bottle. Them using the wrong sound is a bug.

**Pull request closed without merging**
