### PR TITLE
🛡️

### PR DESCRIPTION
**Pull request by Richard-Rogalski**
semi works

current TODO
* fix calculations figuring out if you're facing attacker
* add durability (ez just lazy)
* add textures, sounds, animations
* crafting recipe
* make it so if backhand is used, can't attack when blocking (probably should be implemented on their end)
* add configurations (lots)
* make it not shit
* add arrow bounceback
* make it even less shit

### CODE REVIEW

**Comment by Richard-Rogalski** [comment]
the only things I'd need help on would be 
* add textures, sounds, animations
* fix calculations figuring out if you're facing attacker
I think I got everything else

**Comment by GregoriusT** [comment]
The GitHub warning about "\u{1F6E1}" can be ignored, its just the Unicode character for the Shield Emoji.

What exactly did you do with the Boat Recipes though? You removed their Recipes for some reason?

**Comment by Richard-Rogalski** [comment]
oh, the boat recipies were causing a build failure before I even changed the code, so I just disabled them for the moment

**Comment by Roadhog360** [comment]
Looks like something is still somehow causing a build failure, weird.

**Comment by Roadhog360** [comment]
Closing due to inactive commit and build failure. If you continue this I will reopen

**Pull request closed without merging**
