### PR TITLE
Port Squid Improvements from GTNH BugTorch

### PR DESCRIPTION
**Pull request by glowredman**
As suggested in https://github.com/jss2a98aj/BugTorch/pull/34

### CODE REVIEW

**Comment by Roadhog360** [comment]
This is improper use of Asset Director. You can register just the sound events and skip the entire thing with the dynamic resource pack. That is only needed for cave sounds. Please check how other sounds are registered and used. Additionally, the downloading of the sound should not be conditional.

**Comment by Roadhog360** [comment]
Actually, upon second review, it looks like the squid sounds are already in the mud. I'm not really sure what your code is doing there. So that entire block relating to sounds that you added can be removed because it's already in the mod.

And, of course, the ink cloud should be moved to another config because it's obviously not a sound. Let me think where it should go...

**Comment by Roadhog360** [comment]
- Reference to MCAssetVer prefix in the ink shoot sfx is missing.
- Sound is still tied to duplicate config option instead of the already existing one in the mixins config.

**Comment by Roadhog360** [comment]
Oh and the cloud option should be in catmisc because it's not an entity toggld

**Comment by Roadhog360** [comment]
Looks fine, I'll do the last few tweaks I requested. Thank you

**Comment by Roadhog360** [comment]
@glowredman Just got around to testing this and I can't seem to get the squid particles to appear, any idea why?

**Comment by glowredman** [comment]
Keep in mind that they don't appear all the time but only if
1. `Random.nextDouble()` returns less than 0.15
2. An entity is within a 3x3x3 box of the squid (always given because the attacked squid is there)
3. Of all entities within that box, one is selected at random which must be neither `null` nor the attacked entity

So the resulting chance of particles appearing is `15% * (1 - 1/n)` where n is the number of entities in that 3x3x3 box.

The code could be improved by adding `around.remove(targetEntity);` [here](https://github.com/Roadhog360/Et-Futurum-Requiem/blob/master/src/main/java/ganymedes01/etfuturum/core/handlers/ServerEventHandler.java#L1687) (and consequently removing `target != targetEntity` further down). This would result in the second check turning into a potential early exit (the list is empty -> there is no *other* entity in that 3x3x3 box) and the the third check not lowering the effective chance.

Otherwise I found the code to be working, here is a test in SP where I removed the 15% random chance: https://youtu.be/xbhUH--G6X4

**Pull request merged**
