### PR TITLE
Add backhand code and poorly integrate into ETF

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Adds the Backhand mod to ETF.

I opened this draft PR for you to be able to discuss things and let you the ability to move me to the right direction to match your own thoughts. Not sure if you even like the way I did choose, so let me know any thing you want to change. However, there are still lot things todo, see below.

For integration I orientated me a little bit on how Elytra and Spectator is integrated.

### Todo

- [x] Re-organize structure to fit ETF
- [ ] Extract needed code from Battlegear mod (WIP)
- [x] ~~Mixins?~~
- [x] Integrate config
- [x] Remove unneeded code
- [ ] Baubles

### Not included yet

- mysteriumlib *(removed in port, present in original mod)*
- Battle Gear 2 compatibility *(removed in port, present in original mod)*

### Current state

- ✔️ Build
- ✔️ Existing World load
- ✔️ New World load success
- ✔️ Iventory does render
- ✔️ Can swap items from inventory to offhand and back
- ❌ Offhand does show in 1st person
- ✔️ Offhand does show in 3rd person
- ❌ Offhand can be used to place blocks if main hand is empty or has no right click function

### CODE REVIEW

**Comment by Roadhog360** [comment]
Appreciate the work, I will watch where it goes.

**Comment by Pilzinsel64** [comment]
(Oh dear, this is much bigger then I thought on first look when I started the PR. :/)

Some functions have deep references to the battlegear mod. Most are helper methods but some of them are a bit hacky and random.

What in your opinion should be the goal of it? Should we try keeping hacking code as minimum as possible or do you want a 1 to 1 port of the mod? Also, so we want that hotswap featue?

I may thing about continuing to maintain it as seperate mod as it has really many configurable features and much detailed code that might be too detailed for EFR(?). On the other side, if we could just add the base feature without all that extra configuration but then it would be a downgrade. What do you think?

**Comment by Roadhog360** [comment]
I would be willing to give the offhand dedicated config. As long as the hacks don't pose mod compatibility or performance issues it is honestly ok, just be mindful of what you do.

End goal is to have the offhand functionally identical to its 1.9 counterpart. We can worry about the extra slot after the port is done and working.

**Comment by Pilzinsel64** [comment]
Alright Sir! :)

I'm going to find the missing events I need to get it finally to work and add more documentation to the code, so I can understand it much better.

> For now you can pick some other slot in the inventory.

Well, the dedicated slot is already working using the same slot as the backhand mod (so updating from backhand to etf offhand feature should work, but that's to be tested of course). Using an inventory slot might already work too, but didn't try it yet.

**Comment by Roadhog360** [comment]
Ah I didn't know you'd be using the Backhand slot, ok

**Comment by Pilzinsel64** [comment]
Ok, any idea how I can solve this? Left is the code like it is in Backhand mod and right is the Minecraft class. The fields are private and I have no idea how that can work in Backhand mod and ho to solve that. 🤔 
grafik

**Comment by huihiuhuai** [comment]
please support Angelica's dynamic lights

**Comment by huihiuhuai** [comment]
pleaaase support Angelica's dynamic lights

**Comment by Roadhog360** [comment]
I have changed my stance on large features being in EFR, I have decided big features should probably have their own dedicated mods maintained by me. As such, I will be closing this issue. However if you are still interested in this fork, do know I am considering forking Backhand myself and working on it.

I apologize for the trouble that un-integrating this would be from EFR. To be entirely honest I am not sure 100% if I will even be moving large features out of EFR yet, still, so this may be reopened as well.

**Pull request closed without merging**
