### PR TITLE
Added new config option and translations 

### PR DESCRIPTION
**Pull request by Jerome226**
- Option to disable/enable smooth basalt (was always true)
- Option to disable/enable concrete powder
- Added translation key for boat entity

### CODE REVIEW

**Comment by Jerome226** [comment]
Really small PR so you could also just include it yourself and not merge, but your choice.

**Comment by Roadhog360** [comment]
Typically I bundle very very closely related options together, like how all those blocks were under one option. I'll have to think about the configuration options, I'm a bit on the fence, but if you can tell me a genuinely good use case for this, I'll add it without more questioning.

Interestingly enough, I was actually going to ask what should happen if you have the basalt and calcite disabled, but still have the geode on. Then you fixed it before I got around to writing this.

**Comment by Jerome226** [comment]
im just making a pack where i usually dont want these stone since i use a other mod from them, since smooth sandstone has a option i figured out it was better to just make a seperate option 
for concrete powder its just because i usually want the decoration blocks and dont want to have the pain of placing water on them, i can make it so there a alternative recipe when powder is disabled

you dont really need to merge this but its just for me because i dont really want to just NEI hide

**Comment by Roadhog360** [comment]
I have decided to close this, I will be treating this PR as suggestions and adding similar features. If I end up going back on that and using your code I'll still credit you though

**Comment by Jerome226** [comment]
Any reason for refusing? I just think it's a nice addition to the main mod, but i can understand and hope you add this feature yourself.

**Comment by Roadhog360** [comment]
If I added config options for every single block that would not only involve an exhausting coding process of making sure every code that interacts with every block makes sure it is enabled. I know these two options are not "every single block" but this would open that door because I might get a ton of requests for more individual configuration after this.

When adding configuration, I prefer the options to be a balance of practicality and flexibility. I don't want to bloat the options file with so many block options that it becomes hard to both make and navigate as an end user, but at the same time want to provide such configuration, so I opt for practical options that are likely to be toggled together anyways.

**Pull request closed without merging**
