### PR TITLE
Fix Better Pistons destroying blocks

### PR DESCRIPTION
**Pull request by DrParadox7**
Fixes blocks like Shulker Blocks being destroyed when moved.

Also adds support for BoP honey blocks in Better Pistons

### CODE REVIEW

**Comment by DrParadox7** [comment]
Broken with upstream. Needs revision

**Comment by GregoriusT** [comment]
Shulker Boxes are NOT supposed to be moved by Pistons, it is actually a thing people use in vanilla contraptions to break Shulker Boxes easily by "crushing" them with a Piston.

**Comment by DarianLStephens** [comment]
If they're simply broken in to items, then it's fine, but if the blocks just disappear entirely with no drops? That's bad.

**Comment by Roadhog360** [comment]
> Shulker Boxes are NOT supposed to be moved by Pistons, it is actually a thing people use in vanilla contraptions to break Shulker Boxes easily by "crushing" them with a Piston.

Yes, that was the point. They were being DELETED, not DROPPED.



> If they're simply broken in to items, then it's fine, but if the blocks just disappear entirely with no drops? That's bad.

This exactly.

**Comment by Roadhog360** [comment]
Reverted due to making the issue worse. I ended up reverting within IntelliJ so this PR cannot be re-opened, I probably should not have done that. Please submit a new PR if you revise the fix.

**Pull request merged**
