### PR TITLE
Allow Deepslate Hardness to be configured in the blocks config.

### PR DESCRIPTION
**Pull request by Wmaxlees**
Adds a new int config in the `blocksitems.cfg` file that allows modifying how hard deepslate is. Designed for people that like the look of deepslate but don't want to deal with the additional hardness introduced in their caves.

### CODE REVIEW

**Comment by Wmaxlees** [comment]
Created in reference to this comment: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16436#issuecomment-2143599582

**Comment by Roadhog360** [comment]
Needs work needs to be a float multiplier instead of an int, this also applies to none of the other deepslate blocks. Tiles, bricks, ore all need work, and it needs to be multiplier based.

**Comment by Roadhog360** [comment]
> Updated to a float instead of an int. The stairs, bricks, slabs, etc are all based off of cobbled deepslate. Do you suggest I make cobbled deepslate hardness (and its derivatives) configurable as well? My interpretation of the request is that people may not want to deal with longer mining because they hit the deepslate layer, which cobbled deepslate wouldn't affect.


Yeah, but changing the hardness for just one block in the set wouldn't make any sense. Your config value is still not multiplier based as far as I can understand. The default value should produce the same hardness as vanilla.

> The deepslate ore is 1.5x the configured hardness so is already multiplier based.

You seem to misunderstand my request. I'm saying your change should be a float multiplier that allows this specific value to be configured, and it'd change the other ones to be multiplier-based in the same way. 1.5 = vanilla deepslate 1 = stone

**Comment by Roadhog360** [comment]
This has been planned for a while anyways. If my communication on how this feature should function is insufficient, I can always just do it myself.

**Comment by Roadhog360** [comment]
The problem is we need to figure out how to make them all just one multiplier. It would be quite bloated to have so many different values in the config file for the same feature.

**Comment by Wmaxlees** [comment]
Submitted a change. Let me know what you think. We still have just one config option. The math I wrote above is just part of the code.

**Comment by Roadhog360** [comment]
I think you misunderstood what I meant. I meant configuring the * 1.5 multiplier, not the base hardness. And I have been attempting to theory craft a way where * 1.5 would produce the default values currently in the mod, whereas 0 would produce values identical to the base blocks. We might have to multiply the multiplier, perhaps? Who knows.

The reason why the current suggested solution doesn't work is because it doesn't have a predictable effect on every deepslate block. Your defaults also no longer match the hardnesses in vanilla. It also has no effect on any of the deepslate ores seemingly. The current proposed changes modify the hardness values from vanilla and do not have a consistent effect across all deepslate, and isn't really clear to the player exactly what happens when it's modified, since 2.333333 is a weird value.

**Comment by Wmaxlees** [comment]
Another option would just be to have a flag.

So instead of `deepslateHardness`, we can just use `useStoneHardnessForDeepslate`

And then still just hardcode the hardness for whether that's enabled or not. Then we don't have to deal with any math.

WDYT?

**Comment by Roadhog360** [comment]
I think this is acceptable. Realistically if we made it multiplier based people would probably use 1.5 or 1, making it a flag is a good idea. There are mods that allow adjusting of hardnesses of other mods' blocks so people should use that if they need other values.

I think your idea is probably the best solution. Also should be in functions.cfg btw

**Comment by Roadhog360** [comment]
Looks good. All that's left are the multipliers on the ores, and I can merge it

**Comment by Wmaxlees** [comment]
Sounds good. Tried to make some modifications for ores. Just tested it and it's not working, though.

**Comment by Roadhog360** [comment]
What were you held up on? If you show your failed approaches I will do what I can to spot what went wrong.

**Comment by Wmaxlees** [comment]
Done. Hardness is working with ores now as well.

**Comment by Roadhog360** [comment]
Why the err.println?

**Comment by Wmaxlees** [comment]
Deleted. It was a leftover debug logging I missed deleting.

**Comment by Roadhog360** [comment]
Looks good at a glance. I'll give it one final review after I get home from work.

**Pull request merged**
