### PR TITLE
Composting NEI integration

### PR DESCRIPTION
**Pull request by Yoghurt4C**
hän melkein kertoo hänelle.

### CODE REVIEW

**Comment by GregoriusT** [comment]
Is that supposed to be a Composter NEI Handler? Might be helpful if that was the title instead of a Finnish Relationship Joke.

**Comment by Yoghurt4C** [comment]
but it's funny
image
p.s. the end product does not have quantity labels over the outputs

**Comment by Roadhog360** [comment]
Not gonna be home for another hour. This is nice, wouls you mind changing the title to "Composting" pls?

**Comment by Roadhog360** [comment]
I meant the window title in game lol

**Comment by GregoriusT** [comment]
Wait the Composter produces Dye in EFR? Did not know that, lol.

**Comment by Roadhog360** [comment]
Me when Greg gets trolled

**Pull request merged**
