### PR TITLE
Register more modded ores

### PR DESCRIPTION
**Pull request by Pilzinsel64**
- Register Biomes O' Plenty ores
- Register Draconium ore

### CODE REVIEW

**Comment by DarianLStephens** [comment]
I wonder, could a dynamic registry thing be done, where you supply it textures and the normal variant, and it just creates a new deepslate block?

**Comment by Roadhog360** [comment]
This. Rejected idea.

**Comment by DarianLStephens** [comment]
> Technically GT6 does exactly that, but it wont look as clean as having custom Textures for each Ore. ;)

Oh no, I mean giving it a texture path, or it just generates one based on the block name, and you have to provide it with a resource pack or resourceloader or something.

**Comment by Enterprise12nx01** [comment]
Bumping this, i have many ores that are not generating deepslate variants, such as VoltzEngine, Galacticraft Silicon, etc

**Pull request merged**
