### PR TITLE
Fix wrong "orange cement" translation in ru-RU

### PR DESCRIPTION
**Pull request by iocmet**

### CODE REVIEW

**Comment by Roadhog360** [comment]
@kotmatross28729
What do you think of this?

**Comment by Roadhog360** [comment]
Nvm, this is actually probably right
In every other case where something is orange, `Оранжевый` is used, so this is probably correct.

**Comment by kotmatross28729** [comment]
> @kotmatross28729 What do you think of this?

Oh, sorry, I missed it. Yes, this is a more right version.

**Comment by Roadhog360** [comment]
Thank you for verifying for me, I was just making sure. No need to apologize, your contributions are free and I appreciate them, so don't worry about any errors, we can always just correct them when we find them.

**Pull request merged**
