### PR TITLE
Bamboo Worldgen Config

### PR DESCRIPTION
**Pull request by Wmaxlees**
Add a worldgen config to disable spawnign of bamboo but allowing us to keep the resulting blocks.

### CODE REVIEW

**Comment by Roadhog360** [comment]
How are the blocks are actually obtained with this option enabled?

**Comment by Wmaxlees** [comment]
Other mods provide Bamboo as well (like Biomes o' Plenty). The modpack will have to introduce a recipe to convert or directly create blocks from the other mods bamboo.

**Comment by Roadhog360** [comment]
Ok. Other worldgen options usually have some way to disable it so it fits. Field should be the same as the config string though, and I typically avoid the "enable" prefix in most configs since it's redundant, that's only there in older configs since that's the way it was before I took over.

**Comment by Wmaxlees** [comment]
Done

**Pull request merged**
